# Generated by Django 4.1.3 on 2022-11-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_portfolio_profileimage_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='person_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pesron_info', to='contact.info'),
            preserve_default=False,
        ),
    ]
