# Generated by Django 4.1.3 on 2022-11-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_skill_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.skill'),
            preserve_default=False,
        ),
    ]
