# Generated by Django 4.1.3 on 2022-11-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_info_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='skill',
        ),
        migrations.AddField(
            model_name='info',
            name='skill',
            field=models.ManyToManyField(to='contact.skill'),
        ),
    ]
