# Generated by Django 4.1.3 on 2022-11-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_info_skill_info_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='person_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pesron_info_image', to='contact.info'),
            preserve_default=False,
        ),
    ]
