# Generated by Django 4.1.3 on 2022-11-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_profileimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='pro_image_main',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='pro_image_sub',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/%y/%m/%d'),
        ),
    ]
