# Generated by Django 4.1.3 on 2022-11-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_profileimage_pro_image_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='pimage',
            field=models.ManyToManyField(to='contact.profileimage'),
        ),
    ]
