# Generated by Django 4.1.3 on 2022-11-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_info_pimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='pimage',
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='person_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pesron_info_image', to='contact.info'),
        ),
    ]
