# Generated by Django 4.1.3 on 2022-11-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_remove_info_pimage_alter_profileimage_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='profile_img',
            field=models.ManyToManyField(to='contact.profileimage'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='person_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesron_info_image', to='contact.info'),
        ),
    ]
