# Generated by Django 4.1.3 on 2022-11-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_info_profile_img_alter_profileimage_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='discription',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
