# Generated by Django 4.1.3 on 2022-11-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_alter_info_discription_alter_info_profile_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='info',
            name='Portfolio',
            field=models.ManyToManyField(blank=True, null=True, to='contact.portfolio'),
        ),
        migrations.AddField(
            model_name='info',
            name='pro_image_main',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='info',
            name='pro_image_sub',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='person_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pesron_info_image', to='contact.info'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
