# Generated by Django 4.1.3 on 2022-11-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_remove_info_profile_img_info_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image_detail',
        ),
    ]
